// Course data for Tyrells Wood
export const courses = {
  tyrellsWood: {
    name: "Tyrells Wood",
    courseRating: 70.7,
    slope: 137,
    distance: [
      331, 354, 294, 196, 352, 445, 533, 398, 150, 3053, 336, 338, 525, 405,
      409, 287, 204, 364, 377, 3245, 6298,
    ],
    par: [4, 4, 4, 3, 4, 4, 5, 4, 3, 35, 4, 4, 5, 4, 4, 4, 3, 4, 4, 36, 71],
    strokeIndex: [
      18,
      4,
      16,
      12,
      6,
      1,
      10,
      8,
      14,
      null,
      17,
      7,
      11,
      3,
      2,
      15,
      9,
      5,
      13,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null, // Out
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null, // In
      null, // Tot
    ],
  },
  silvertip: {
    name: "Silvertip",
    courseRating: 69.0,
    slope: 129,
    distance: [
      285, 426, 174, 360, 363, 170, 291, 455, 368, 2892, 464, 359, 308, 377,
      496, 171, 310, 182, 385, 3052, 5944,
    ],
    par: [4, 5, 3, 4, 4, 3, 4, 5, 4, 36, 5, 4, 4, 4, 5, 3, 4, 3, 4, 36, 72],
    strokeIndex: [
      14,
      8,
      18,
      6,
      10,
      16,
      12,
      4,
      2,
      null,
      3,
      11,
      15,
      5,
      1,
      13,
      9,
      17,
      7,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      null,
    ],
  },
  stewartCreek: {
    name: "Stewart Creek",
    courseRating: 68.7,
    slope: 123,
    distance: [
      340, 492, 159, 421, 368, 487, 356, 216, 187, 3026, 358, 544, 188, 379,
      259, 389, 414, 144, 467, 3142, 6168,
    ],
    par: [4, 5, 3, 4, 4, 5, 4, 3, 3, 35, 4, 5, 3, 4, 4, 4, 4, 3, 5, 36, 71],
    strokeIndex: [
      9,
      5,
      17,
      1,
      7,
      3,
      11,
      13,
      15,
      null,
      12,
      2,
      18,
      10,
      14,
      6,
      4,
      16,
      8,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      null,
    ],
  },
  luffenhamHeath: {
    name: "Luffenham Heath",
    courseRating: 70.9,
    slope: 132,
    distance: [
      352, 404, 381, 399, 151, 491, 387, 313, 169, 3047, 386, 435, 165, 469,
      360, 397, 407, 197, 555, 3371, 6418,
    ],
    par: [4, 4, 4, 4, 3, 5, 4, 4, 3, 35, 4, 4, 3, 4, 4, 4, 4, 3, 5, 35, 70],
    strokeIndex: [
      10,
      4,
      8,
      14,
      16,
      2,
      6,
      18,
      12,
      null,
      9,
      3,
      17,
      1,
      15,
      5,
      7,
      11,
      13,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      null,
    ],
  },
  sauntonEast: {
    name: "Saunton East",
    courseRating: 70.0,
    slope: 113,
    distance: [
      478, 526, 402, 441, 122, 370, 428, 380, 392, 3539, 337, 362, 414, 145,
      455, 478, 434, 207, 408, 3240, 6779,
    ],
    par: [4, 5, 4, 4, 3, 4, 4, 4, 4, 36, 4, 4, 4, 3, 4, 5, 4, 3, 4, 35, 71],
    strokeIndex: [
      5,
      13,
      9,
      1,
      17,
      15,
      3,
      11,
      7,
      null,
      8,
      12,
      4,
      18,
      2,
      14,
      6,
      16,
      10,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      null,
    ],
  },
  sauntonWest: {
    name: "Saunton West",
    courseRating: 70.0,
    slope: 113,
    distance: [
      361, 367, 475, 208, 412, 404, 423, 415, 152, 3217, 573, 212, 551, 416,
      441, 303, 187, 503, 193, 3379, 6596,
    ],
    par: [4, 4, 5, 3, 4, 4, 4, 4, 3, 35, 5, 3, 5, 4, 4, 4, 3, 5, 3, 36, 71],
    strokeIndex: [
      10,
      6,
      12,
      16,
      4,
      8,
      2,
      14,
      18,
      null,
      3,
      15,
      9,
      5,
      1,
      11,
      17,
      7,
      13,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      null,
    ],
  },
  royalOstend: {
    name: "Royal Ostend",
    courseRating: 70.3,
    slope: 121,
    distance: [
      286, 449, 184, 335, 397, 133, 473, 150, 378, 2785, 398, 139, 299, 161,
      446, 253, 329, 191, 505, 2721, 5506,
    ],
    par: [4, 5, 3, 4, 4, 3, 5, 3, 4, 35, 4, 3, 4, 3, 5, 4, 4, 3, 5, 35, 70],
    strokeIndex: [
      15,
      5,
      7,
      9,
      1,
      17,
      3,
      13,
      11,
      null,
      2,
      16,
      12,
      4,
      8,
      18,
      6,
      14,
      10,
      null,
      null,
    ],
    holeRating: [
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      5,
      null,
      null,
    ],
  },
  royalZoute: {
    name: "Royal Zoute",
    location: 'Belgium, West Flanders',
    teePlayed: 'MBA',
    playedIn: ['2025'],
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: 'https://www.rzgc.be/',
    description: '',
    photos: ['', '', '', ''],
    courseRating: 72.3,
    slope: 126,
    distance: [
      378, 353, 135, 355, 435, 373, 346, 181, 389, 2945,
      344, 164, 474, 431, 337, 431, 159, 491, 379, 3210, 6155,
    ],
    par: [
      4, 4, 3, 4, 5, 4, 4, 3, 4, 35,
      4, 3, 5, 4, 4, 5, 3, 5, 4, 37, 72,
    ],
    strokeIndex: [
       5, 11, 17, 9, 13, 1, 7, 15, 3, null,
       8, 16, 14, 2, 4, 10, 18, 12, 6, null, null,
    ],
    holeRating: [
      null, null, null, null, null, null, null, null, null,
      null,
      null, null, null, null, null, null, null, null, null,
      null,
      null,
    ],
  },
  westSussex: {
    name: "West Sussex",
    location: 'England, West Sussex',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  eastBrighton: {
    name: "East Brighton",
    location: 'England, East Sussex',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  chobham: {
    name: "Chobham",
    location: 'England, Surrey',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  hindhead: {
    name: "Hindhead",
    location: 'England, Surrey',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  camberleyHeath: {
    name: "Camberley Heath",
    location: 'England, Surrey',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  royalStDavids: {
    name: "Royal St Davids",
    location: 'Wales, Gwynedd',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  royalAshdown: {
    name: "Royal Ashdown",
    location: 'England, East Sussex',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  westHill: {
    name: "West Hill",
    location: 'England, Surrey',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  swinleyForest: {
    name: "Swinley Forest",
    location: 'England, Berkshire',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  pleasington: {
    name: "Pleasington",
    location: 'England, Lancashire',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  carbrook: {
    name: "Carbrook",
    location: 'Australia, Queensland',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  theGlades: {
    name: "The Glades",
    location: 'Australia, Queensland',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  byronBay: {
    name: "Byron Bay",
    location: 'Australia, New South Wales',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  brookwater: {
    name: "Brookwater",
    location: 'Australia, Queensland',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
  royalQueensland: {
    name: "Royal Queensland",
    location: 'Australia, Queensland',
    teePlayed: null,
    playedIn: null,
    ratings: {
      holeTierRatings: [],
      courseRating54: null,
      facilityRatings: {
        locationEaseOfAccess: null,
        valueForMoney: null,
        postRoundVibes: null,
        clubhouse: null,
        golfFacilities: null,
        courseMap: null,
      },
      facilities46: null,
      total100: null,
    },
    holeTierSummary: null,
    website: '',
    description: '',
    photos: ['', '', '', ''],
    courseRating: null,
    slope: null,
    distance: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    par: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    strokeIndex: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    holeRating: [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  },
};

const holeLabels = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  "Out",
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  "In",
  "Tot",
];

function getCourseData(courseName) {
  return courses[courseName] || null;
}

function getAllCourses() {
  return courses;
}
